Err(
    consumed=33,
    reason="unexpected token or incomplete construct",
    final_reason="final failure at next unconsumed token",
    prev_token=[6:2 len=1] Token,
    next_token=[0:0 len=0] Eof,
    partial_ast=SourceFile(
    Attr_End,
    Namespace(
      Path_Cons(
        "parser",
        Path_Cons(
          "error",
          Path_Cons(
            "route",
            Path_Cons(
              "missing",
              Path_Cons(
                "ns",
                Path_End
              )
            )
          )
        )
      )
    ),
    Item_Cons(
      Item_Def(
        DefItem2(
          "missing_via_namespace",
          DefFun(
            Generic_End,
            Param_Cons(
              Param(
                "value",
                Type_Path(
                  "i64",
                  Type_Tail_End
                )
              ),
              Param_End
            ),
            Type_Path(
              "i64",
              Type_Tail_End
            ),
            Expr_Block(
              Stmt_Cons(
                Stmt_LetPatternTyped(
                  Pattern_IdentStart(
                    "routed",
                    PatternAfterIdent_Atom(
                      PatternIdent_Name
                    )
                  ),
                  Type_Path(
                    "",
                    Type_Tail_End
                  ),
                  Expr_ParenIdent(
                    "value",
                    ParenIdent_Binary(
                      Null,
                      Null
                    )
                  )
                ),
                Stmt_Cons(
                  Stmt_Expr(
                    Expr_IdentTail(
                      "routed",
                      IdentTail_None
                    )
                  ),
                  Stmt_End
                )
              ),
              TailExpr_None
            )
          )
        )
      ),
      Item_End
    )
  )
)
0
