OK(
  SourceFile(
    Attr_End,
    Namespace(
      Path_Cons(
        "lexer",
        Path_Cons(
          "spec",
          Path_Cons(
            "externasm",
            Path_End
          )
        )
      )
    ),
    Item_Cons(
      Item_Def(
        DefItem2(
          DefName(
            "puts",
            Generic_End,
            DefNamePlain
          ),
          DefFun(
            Generic_End,
            Param_Cons(
              Param(
                "msg",
                Type_Path(
                  "cstr",
                  Type_Tail_End
                )
              ),
              Param_End
            ),
            Type_Path(
              "i32",
              Type_Tail_End
            ),
            Expr_ExternImport(
              "c",
              "puts"
            )
          )
        )
      ),
      Item_Cons(
        Item_Def(
          DefItem2(
            DefName(
              "cbx_entry",
              Generic_End,
              DefNamePlain
            ),
            DefFun(
              Generic_End,
              Param_Cons(
                Param(
                  "x",
                  Type_Path(
                    "i64",
                    Type_Tail_End
                  )
                ),
                Param_End
              ),
              Type_Path(
                "i64",
                Type_Tail_End
              ),
              Expr_ExternImport(
                "cbx",
                "cbx_entry"
              )
            )
          )
        ),
        Item_Cons(
          Item_Def(
            DefItem2(
              DefName(
                "low_level",
                Generic_End,
                DefNamePlain
              ),
              DefFun(
                Generic_End,
                Param_Cons(
                  Param(
                    "ptr",
                    Type_Path(
                      "Ptr",
                      Type_Tail_Generic(
                        TypeArg_Cons(
                          Type_Path(
                            "u8",
                            Type_Tail_End
                          ),
                          TypeArg_End
                        )
                      )
                    )
                  ),
                  Param_Cons(
                    Param(
                      "idx",
                      Type_Path(
                        "i64",
                        Type_Tail_End
                      )
                    ),
                    Param_End
                  )
                ),
                Type_Path(
                  "i64",
                  Type_Tail_End
                ),
                Expr_Unsafe(
                  Expr_Block(
                    Stmt_Cons(
                      Stmt_LetPatternTyped(
                        Pattern_IdentStart(
                          "loaded",
                          PatternAfterIdent_Atom(
                            PatternIdent_Name
                          )
                        ),
                        Type_Path(
                          "u8",
                          Type_Tail_End
                        ),
                        Expr_Deref(
                          Expr_IdentTail(
                            "ptr",
                            IdentTail_None
                          )
                        )
                      ),
                      Stmt_Cons(
                        Stmt_LetPatternTyped(
                          Pattern_IdentStart(
                            "v",
                            PatternAfterIdent_Atom(
                              PatternIdent_Name
                            )
                          ),
                          Type_Path(
                            "",
                            Type_Tail_End
                          ),
                          Expr_Asm(
                            AsmBind_Cons(
                              AsmBind(
                                "ptr",
                                "rdi"
                              ),
                              AsmBind_Cons(
                                AsmBind(
                                  "idx",
                                  "rsi"
                                ),
                                AsmBind_End
                              )
                            ),
                            AsmOutput_Cons(
                              "rax",
                              AsmOutput_End
                            ),
                            AsmString_Cons(
                              Expr_String,
                              AsmString_Cons(
                                Expr_String,
                                AsmString_End
                              )
                            )
                          )
                        ),
                        Stmt_Cons(
                          Stmt_Return(
                            Expr_IdentTail(
                              "v",
                              IdentTail_None
                            )
                          ),
                          Stmt_End
                        )
                      )
                    ),
                    TailExpr_None
                  )
                )
              )
            )
          ),
          Item_End
        )
      )
    )
  )
)
0
