OK(
  SourceFile(
    Attr_End,
    Namespace(
      Path_Cons(
        "parser",
        Path_Cons(
          "spec",
          Path_Cons(
            "cast",
            Path_Cons(
              "route",
              Path_Cons(
                "generic",
                Path_End
              )
            )
          )
        )
      )
    ),
    Item_Cons(
      Item_Def(
        DefItem2(
          "route",
          DefFun(
            Generic_Cons(
              GenericParam(
                "T",
                GenericBound_Cons(
                  GenericBound_Nominal(
                    "Nominal"
                  ),
                  GenericBound_Cons(
                    GenericBound_Nominal(
                      "N2"
                    ),
                    GenericBound_Cons(
                      GenericBound_Row(
                        GenericRow(
                          "x",
                          GenericRowField_Cons(
                            GenericRowField(
                              "id",
                              Type_Path(
                                "i64",
                                Type_Tail_End
                              )
                            ),
                            GenericRowField_Cons(
                              GenericRowField(
                                "name",
                                Type_Path(
                                  "String",
                                  Type_Tail_End
                                )
                              ),
                              GenericRowField_End
                            )
                          )
                        )
                      ),
                      GenericBound_End
                    )
                  )
                )
              ),
              Generic_Cons(
                GenericParam(
                  "F",
                  GenericBound_End
                ),
                Generic_End
              )
            ),
            Param_Cons(
              Param(
                "value",
                Type_Path(
                  "T",
                  Type_Tail_End
                )
              ),
              Param_Cons(
                Param(
                  "mapper",
                  Type_Path(
                    "F",
                    Type_Tail_End
                  )
                ),
                Param_End
              )
            ),
            Type_Path(
              "i64",
              Type_Tail_End
            ),
            Expr_Block(
              Stmt_Cons(
                Stmt_LetPatternTyped(
                  Pattern_IdentStart(
                    "casted",
                    PatternAfterIdent_Atom(
                      PatternIdent_Name
                    )
                  ),
                  Type_Path(
                    "",
                    Type_Tail_End
                  ),
                  Expr_Cast(
                    Expr_IdentTail(
                      "value",
                      IdentTail_None
                    ),
                    Type_Path(
                      "primitive",
                      Type_Tail_End
                    )
                  )
                ),
                Stmt_Cons(
                  Stmt_LetPatternTyped(
                    Pattern_IdentStart(
                      "routed",
                      PatternAfterIdent_Atom(
                        PatternIdent_Name
                      )
                    ),
                    Type_Path(
                      "",
                      Type_Tail_End
                    ),
                    Expr_Via(
                      Expr_Call(
                        Expr_Index(
                          Expr_IdentTail(
                            "f",
                            IdentTail_None
                          ),
                          ExprList_Cons(
                            Expr_IdentTail(
                              "T",
                              IdentTail_None
                            ),
                            ExprList_Cons(
                              Expr_IdentTail(
                                "F",
                                IdentTail_None
                              ),
                              ExprList_End
                            )
                          )
                        ),
                        Arg_Cons(
                          Expr_IdentTail(
                            "casted",
                            IdentTail_None
                          ),
                          Arg_Cons(
                            Expr_IdentTail(
                              "mapper",
                              IdentTail_None
                            ),
                            Arg_End
                          )
                        )
                      ),
                      Path_Cons(
                        "runtime",
                        Path_Cons(
                          "dispatch",
                          Path_End
                        )
                      )
                    )
                  ),
                  Stmt_Cons(
                    Stmt_Expr(
                      Expr_IdentTail(
                        "routed",
                        IdentTail_None
                      )
                    ),
                    Stmt_End
                  )
                )
              ),
              TailExpr_None
            )
          )
        )
      ),
      Item_End
    )
  )
)
0
