OK(
  SourceFile(
    Attr_End,
    Namespace(
      Path_Cons(
        "parser",
        Path_Cons(
          "spec",
          Path_Cons(
            "iface",
            Path_Cons(
              "dynamic",
              Path_Cons(
                "contract",
                Path_End
              )
            )
          )
        )
      )
    ),
    Item_Cons(
      Item_Interface(
        InterfaceItem(
          "NominalInterface",
          InterfaceMethod_Cons(
            InterfaceMethod(
              "render",
              Param_End,
              Type_Path(
                "String",
                Type_Tail_End
              )
            ),
            InterfaceMethod_Cons(
              InterfaceMethod(
                "map",
                Param_Cons(
                  Param(
                    "value",
                    Type_Path(
                      "i64",
                      Type_Tail_End
                    )
                  ),
                  Param_End
                ),
                Type_Path(
                  "i64",
                  Type_Tail_End
                )
              ),
              InterfaceMethod_End
            )
          )
        )
      ),
      Item_Cons(
        Item_Def(
          DefItem2(
            "use_dyn",
            DefFun(
              Generic_End,
              Param_Cons(
                Param(
                  "value",
                  Type_Dyn(
                    DynType_Cons(
                      DynType_Nominal(
                        "NominalInterface"
                      ),
                      DynType_Cons(
                        DynType_Nominal(
                          "Nominal2"
                        ),
                        DynType_Cons(
                          DynType_Row(
                            DynRow(
                              "row",
                              DynRowField_Cons(
                                DynRowField(
                                  "poly",
                                  Type_Path(
                                    "String",
                                    Type_Tail_End
                                  )
                                ),
                                DynRowField_End
                              )
                            )
                          ),
                          DynType_End
                        )
                      )
                    )
                  )
                ),
                Param_End
              ),
              Type_Dyn(
                DynType_Cons(
                  DynType_Nominal(
                    "NominalInterface"
                  ),
                  DynType_Cons(
                    DynType_Nominal(
                      "Nominal2"
                    ),
                    DynType_Cons(
                      DynType_Row(
                        DynRow(
                          "row",
                          DynRowField_Cons(
                            DynRowField(
                              "poly",
                              Type_Path(
                                "String",
                                Type_Tail_End
                              )
                            ),
                            DynRowField_End
                          )
                        )
                      ),
                      DynType_End
                    )
                  )
                )
              ),
              Expr_IdentTail(
                "value",
                IdentTail_None
              )
            )
          )
        ),
        Item_End
      )
    )
  )
)
0
