OK(
  SourceFile(
    Attr_End,
    Namespace(
      Path_Cons(
        "parser",
        Path_Cons(
          "spec",
          Path_Cons(
            "receiver",
            Path_Cons(
              "keyword",
              Path_End
            )
          )
        )
      )
    ),
    Item_Cons(
      Item_Def(
        DefItem2(
          "take_self",
          DefFun(
            Generic_End,
            Param_End,
            Type_Path(
              "i64",
              Type_Tail_End
            ),
            Expr_Block(
              Stmt_Cons(
                Stmt_LetPatternTyped(
                  Pattern_IdentStart(
                    "value",
                    PatternAfterIdent_Atom(
                      PatternIdent_Name
                    )
                  ),
                  Type_Path(
                    "",
                    Type_Tail_End
                  ),
                  Expr_Name(
                    "self"
                  )
                ),
                Stmt_Cons(
                  Stmt_Expr(
                    Expr_IdentTail(
                      "value",
                      IdentTail_None
                    )
                  ),
                  Stmt_End
                )
              ),
              TailExpr_None
            )
          )
        )
      ),
      Item_End
    )
  )
)
0
