OK(
  SourceFile(
    Attr_End,
    Namespace(
      Path_Cons(
        "parser",
        Path_Cons(
          "spec",
          Path_Cons(
            "nominal",
            Path_Cons(
              "generic",
              Path_Cons(
                "record",
                Path_End
              )
            )
          )
        )
      )
    ),
    Item_Cons(
      Item_Type(
        TypeItem(
          "ABC",
          Generic_Cons(
            GenericParam(
              "T",
              GenericBound_Cons(
                GenericBound_Nominal(
                  "X"
                ),
                GenericBound_Cons(
                  GenericBound_Nominal(
                    "Y"
                  ),
                  GenericBound_Cons(
                    GenericBound_Row(
                      GenericRow(
                        "z",
                        GenericRowField_Cons(
                          GenericRowField(
                            "row",
                            Type_Path(
                              "Type",
                              Type_Tail_End
                            )
                          ),
                          GenericRowField_End
                        )
                      )
                    ),
                    GenericBound_End
                  )
                )
              )
            ),
            Generic_Cons(
              GenericParam(
                "F",
                GenericBound_End
              ),
              Generic_End
            )
          ),
          NominalField_Cons(
            NominalField(
              "a",
              Type_Path(
                "T",
                Type_Tail_End
              )
            ),
            NominalField_Cons(
              NominalField(
                "b",
                Type_Path(
                  "F",
                  Type_Tail_End
                )
              ),
              NominalField_End
            )
          )
        )
      ),
      Item_End
    )
  )
)
0
