OK(
  SourceFile(
    Attr_End,
    Namespace(
      Path_Cons(
        "parser",
        Path_Cons(
          "spec",
          Path_Cons(
            "method",
            Path_Cons(
              "receiver",
              Path_Cons(
                "generics",
                Path_End
              )
            )
          )
        )
      )
    ),
    Item_Cons(
      Item_Def(
        DefItem2(
          DefName(
            "Generic",
            Generic_Cons(
              GenericParam(
                "T",
                GenericBound_Cons(
                  GenericBound_Nominal(
                    "X"
                  ),
                  GenericBound_Cons(
                    GenericBound_Nominal(
                      "Y"
                    ),
                    GenericBound_Cons(
                      GenericBound_Row(
                        GenericRow(
                          "z",
                          GenericRowField_Cons(
                            GenericRowField(
                              "row",
                              Type_Path(
                                "Type",
                                Type_Tail_End
                              )
                            ),
                            GenericRowField_End
                          )
                        )
                      ),
                      GenericBound_End
                    )
                  )
                )
              ),
              Generic_Cons(
                GenericParam(
                  "F",
                  GenericBound_End
                ),
                Generic_End
              )
            ),
            DefNameMethod(
              "method"
            )
          ),
          DefFun(
            Generic_Cons(
              GenericParam(
                "X",
                GenericBound_End
              ),
              Generic_Cons(
                GenericParam(
                  "Y",
                  GenericBound_End
                ),
                Generic_End
              )
            ),
            Param_Cons(
              Param(
                "value",
                Type_Path(
                  "X",
                  Type_Tail_End
                )
              ),
              Param_Cons(
                Param(
                  "fallback",
                  Type_Path(
                    "Y",
                    Type_Tail_End
                  )
                ),
                Param_End
              )
            ),
            Type_Path(
              "X",
              Type_Tail_End
            ),
            Expr_IdentTail(
              "value",
              IdentTail_None
            )
          )
        )
      ),
      Item_End
    )
  )
)
0
