OK(
  SourceFile(
    Attr_End,
    Namespace(
      Path_Cons(
        "parser",
        Path_Cons(
          "spec",
          Path_Cons(
            "bittype",
            Path_End
          )
        )
      )
    ),
    Item_Cons(
      Item_Bittype(
        BittypeItem(
          "EtherHeader",
          Generic_End,
          BitField_Cons(
            BitField(
              "dst",
              BitFieldType_Named(
                "bytes",
                BitFieldType_Args(
                  Arg_Cons(
                    Expr_Int(
                      "6"
                    ),
                    Arg_End
                  )
                )
              )
            ),
            BitField_Cons(
              BitField(
                "src",
                BitFieldType_Named(
                  "bytes",
                  BitFieldType_Args(
                    Arg_Cons(
                      Expr_Int(
                        "6"
                      ),
                      Arg_End
                    )
                  )
                )
              ),
              BitField_Cons(
                BitField(
                  "ethertype",
                  BitFieldType_Named(
                    "u16_be",
                    BitFieldType_NoArgs
                  )
                ),
                BitField_End
              )
            )
          )
        )
      ),
      Item_End
    )
  )
)
0
