OK(
  SourceFile(
    Attr_End,
    Namespace(
      Path_Cons(
        "parser",
        Path_Cons(
          "spec",
          Path_Cons(
            "bittype",
            Path_Cons(
              "pattern",
              Path_End
            )
          )
        )
      )
    ),
    Item_Cons(
      Item_Def(
        DefItem2(
          DefName(
            "f",
            Generic_End,
            DefNamePlain
          ),
          DefFun(
            Generic_End,
            Param_Cons(
              Param(
                "b",
                Type_Path(
                  "Bytes",
                  Type_Tail_End
                )
              ),
              Param_End
            ),
            Type_Path(
              "i64",
              Type_Tail_End
            ),
            Expr_Match(
              Expr_MatchIdent(
                "b",
                MatchIdent_Name
              ),
              MatchArm_Cons(
                MatchArm(
                  Pattern_Bit(
                    BitPatField_Cons(
                      BitPatField_Bind(
                        "n",
                        BitFieldType_Named(
                          "u8",
                          BitFieldType_NoArgs
                        )
                      ),
                      BitPatField_End
                    )
                  ),
                  MatchGuard_None,
                  Expr_Int(
                    "1"
                  )
                ),
                MatchArm_Cons(
                  MatchArm(
                    Pattern_IdentStart(
                      "_",
                      PatternAfterIdent_Atom(
                        PatternIdent_Name
                      )
                    ),
                    MatchGuard_None,
                    Expr_Int(
                      "0"
                    )
                  ),
                  MatchArm_End
                )
              )
            )
          )
        )
      ),
      Item_End
    )
  )
)
0
